### ISSUE TITLE
KeyError: 'elements'

### ISSUE THREAD

**Issue by viveksml** [liranbg/linkedin-learning-downloader#7]
pl note the following error:

Traceback (most recent call last):
  File "linkedin_learning.py", line 226, in <module>
    loop.run_until_complete(process())
  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 467, in run_until_complete
    return future.result()
  File "linkedin_learning.py", line 214, in process
    await fetch_courses()
  File "linkedin_learning.py", line 102, in fetch_courses
    return await asyncio.gather(*map(fetch_course, COURSES))
  File "linkedin_learning.py", line 112, in fetch_course
    course = build_course(data['elements'][0])
KeyError: 'elements'

**Comment by slotbite** [comment]
Traceback (most recent call last):
  File "...........linkedin_learning.py", line 247, in <module>
    loop.run_until_complete(process())
  File "C:\Users\..............\AppData\Local\conda\conda\envs\cnn\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "c:..........linkedin_learning.py", line 235, in process
    await fetch_courses()
  File "c:........linkedin_learning.py", line 108, in fetch_courses
    return await asyncio.gather(*map(fetch_course, COURSES))
  File "c:......../linkedin_learning.py", line 124, in fetch_course
    course = build_course(data['elements'][0])
KeyError: 'elements'

The data var return en 111 line: async def fetch_course(course_slug): ....... {'status': 404}

**Comment by vincthedwarf** [comment]
Traceback (most recent call last):
  File "linkedin_learning.py", line 226, in <module>
    loop.run_until_complete(process())
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 568, in run_until_complete
    return future.result()
  File "linkedin_learning.py", line 214, in process
    await fetch_courses()
  File "linkedin_learning.py", line 102, in fetch_courses
    return await asyncio.gather(*map(fetch_course, COURSES))
  File "linkedin_learning.py", line 112, in fetch_course
    course = build_course(data['elements'][0])
KeyError: 'elements'

**Comment by hyber-code** [comment]
Traceback (most recent call last):
  File "linkedin_learning.py", line 226, in <module>
    loop.run_until_complete(process())
  File "C:\Users\Sohail.Akram\Anaconda3\lib\asyncio\base_events.py", line 568, in run_until_complete
    return future.result()
  File "linkedin_learning.py", line 214, in process
    await fetch_courses()
  File "linkedin_learning.py", line 102, in fetch_courses
    return await asyncio.gather(*map(fetch_course, COURSES))
  File "linkedin_learning.py", line 112, in fetch_course
    course = build_course(data['elements'][0])
KeyError: 'elements'

**Comment by vincthedwarf** [comment]
I tried with this one and it worked
https://github.com/pedromarthon/linkedin_learning_courses_downloader

**Comment by slotbite** [comment]
> I tried with this one and it worked
> https://github.com/pedromarthon/linkedin_learning_courses_downloader

Yes its works nice , but some course titles , code break in the unicode characters u'\ux201.....blabalbla , this repo is more complete and smart because download the material (zip) ,and other characteristics

**Comment by hyber-code** [comment]
there was a regularly updated repo here on github , however it was taken down by dmca , so i suppose this is what we got

**Comment by hyber-code** [comment]
and it seems that linkedin has been hunting the repos here, and linkedin also changed some of their code, therefore, the repos here have stopped working.

**Comment by hyber-code** [comment]
> 
> 
> I tried with this one and it worked
> https://github.com/pedromarthon/linkedin_learning_courses_downloader

which python version you are using i am getting the same element error on python 2

**Comment by vincthedwarf** [comment]
I am using Python 3 on a mac.
I am a premium member.
I am using it to download all the content of a course to watch it offline.
That saves me a lot of time as I don't have to dowmload every part one by one.

**Comment by hyber-code** [comment]
> 
> 
> I am using Python 3 on a mac.
> I am a premium member.
> I am using it to download all the content of a course to watch it offline.
> That saves me a lot of time as I don't have to dowmload every part one by one.
 iam also a premium member , when i run the code in python3 it gives urllib2 error as it is only for python2 , if i run through python2 it gives same old errror of elements posted at top.

if you dont mind can you please share the code you are using ?

**Comment by vincthedwarf** [comment]
I will do it Monday :)

**Comment by vincthedwarf** [comment]
Let me know if this works
I am using a Mac and I am a Premium Linkedin user,  everything works 100% on my side
[](https://drive.google.com/drive/folders/1qNV8rI40Imb83JiL4JkqTknHiviO5ys9?usp=sharing)

**Comment by vincthedwarf** [comment]
https://drive.google.com/drive/folders/1qNV8rI40Imb83JiL4JkqTknHiviO5ys9?usp=sharing

**Comment by vincthedwarf** [comment]
Type "python --version"
Try with python 2, do you get the same error?

**Comment by vincthedwarf** [comment]
In the config.py line 4 there is a quotation mark delete it, I did this
typo when I deleted my password.
I updated the file in the drive as well.

**Comment by vincthedwarf** [comment]
Type 'python --version' in the terminal
I am using python 2
In the config.py line 4 there is a quotation mark delete it, I did this
typo when I deleted my password.
I updated the file in the drive as well.
I did the test and everything is working well on my side.
Let me know if its working now.

**Comment by vincthedwarf** [comment]
Type 'python --version' in the terminal
I am using python 2
I updated the files in the drive and compressed it.
I did the test and everything is working well on my side.
Let me know if its working now.

**Comment by hyber-code** [comment]
dear share the link of compressed file , if i click on the last link (google drive )it says the folder is in owner's bin

**Comment by vincthedwarf** [comment]
I am a Premium Linkedin user.
I am using python 2 on a Mac.
Type 'python2 llcd.py' in the terminal
I did the test and everything is working well on my side.
This script doesn't download the exercise files only the videos.
You can easily find the exercise files on Linkedin Learning. 
You will find the scripts here:
https://drive.google.com/file/d/1tH2YNL6jyGWxJ6TsgH9eH_rYZa3IAxsS/view?usp=sharing

**Comment by vincthedwarf** [comment]
Please delete all comments that are not useful anymore

**Comment by hyber-code** [comment]
finally!! thank a lot it is working , hope it downloads the excersise files also . However, it started working with the previous file when i used python2.

dear really appreciate for your help. keep smiling :).

```
C:\2e>python2 llcd.py
[*] Obtained new session: *****

[*] Parsing "Illustrator for Fashion Design Drawing Flats" course's chapters
[*] [12 chapters found]
[*] --- Parsing "Introduction" chapters's videos
[*] --- [3 videos found]
[*] ------ Downloading video "Welcome"
[*] ------ Downloading video "What is a CAD flat"
[*] ------ Downloading video "Using the exercise files"
[*] --- Parsing "1. Getting Started The Basics" chapters's videos
[*] --- [9 videos found]
[*] ------ Downloading video "Exploring the workspace"
[*] ------ Downloading video "Using selection tools"
[*] ------ Downloading video "Drawing shapes"
[*] ------ Downloading video "Using color"
[*] ------ Downloading video "Using the Layers panel"
[*] ------ Downloading video "Using the Rotate tool"
[*] ------ Downloading video "Using the Pen tool"
[*] ------ Downloading video "Using the Reflect and Join commands"
[*] ------ Downloading video "Using Pathfinder and Shape Builder"
[*] --- Parsing "2. Creating a Start File" chapters's videos
[*] --- [3 videos found]

```

**Comment by vincthedwarf** [comment]
You are welcome!
Please delete all comment that are not helpful. That will makes this issue lighter to read for others :)

**Comment by hyber-code** [comment]
> 
> 
> Hyber-code
> You are welcome!
> Please delete all comment that are not helpful. That will makes this issue lighter to read for others :)

yes i already deleted extra comments , please note that you shared the zip file of 708.xx mb  , may be it includes one of your courses also.

**Comment by vincthedwarf** [comment]
Ok I did the update in the zip file! Thanks
Could you delete your last comment :)
Let me know if you need more support

**Comment by vincthedwarf** [comment]
Hi viveksml,
Can you close this issue, since it has been resolved?
Best regards.
Vinc

**Comment by armandhammer** [comment]
I was seeing the same `KeyError: 'elements'` earlier today and it seems to be a problem on Linkedin's end, and not with the script. I was downloading videos fine for a couple hours today (pulled down probably 20 GB) and suddenly everything stopped working and I got that error. But now I can't access the Linkedin Learning site AT ALL on the web — after I log in, every Learning link is just a blank page (Chrome says it's HTTP ERROR 429, Firefox just shows a white page). I chatted with Linkedin Learning support, and they  have no idea what is going on so they escalated the issue. I'm waiting to hear back (of course I won't mention I am using a script to d/l video courses). Regular Linkedin is fine, but it appears I am maybe banned from the Learning site for pulling down too many videos today?

**Comment by armandhammer** [comment]
Turns out it was a server error 429 for downloading too much stuff in too short of a time period. This is fairly common and was probably just an automatic server response, and not anything that LinkedIn Learning did specifically due to my downloading activity. I checked again in the morning and it's working fine. My guess is if you get 429'd it clears itself up after 12 hours.

**Comment by nathan-never** [comment]
Guys, 
I still have the same problem as per below and I can access Linkedin Learning.
I have tried from few IP addresses but the issue is still the same.
Any idea?

Thank you 
Nathan

==============================================================
2019-01-16 09:04:51,598 asyncio      DEBUG    Using selector: KqueueSelector
2019-01-16 09:04:51,599 root         INFO     [*] -------------Login-------------
2019-01-16 09:04:51,599 root         INFO     [*] Login step 1 - Getting CSRF token...
2019-01-16 09:04:52,279 root         DEBUG    [*] CSRF: b796eb0a-337e-4cf5-8714-48f04d3249eb
2019-01-16 09:04:52,279 root         INFO     [*] Login step 1 - Done
2019-01-16 09:04:52,279 root         INFO     [*] Login step 2 - Logging In...
2019-01-16 09:04:53,341 root         INFO     [*] Login step 2 - Done
2019-01-16 09:04:53,342 root         INFO     [*] -------------Done-------------
2019-01-16 09:04:53,342 root         INFO     [*] -------------Fetching Course-------------
Traceback (most recent call last):
  File "linkedin_learning.py", line 226, in <module>
    loop.run_until_complete(process())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "linkedin_learning.py", line 214, in process
    await fetch_courses()
  File "linkedin_learning.py", line 102, in fetch_courses
    return await asyncio.gather(*map(fetch_course, COURSES))
  File "linkedin_learning.py", line 112, in fetch_course
    course = build_course(data['elements'][0])
KeyError: 'elements'

**Comment by nathan-never** [comment]
> finally!! thank a lot it is working , hope it downloads the excersise files also . However, it started working with the previous file when i used python2.
> 
> dear really appreciate for your help. keep smiling :).
> 
> ```
> C:\2e>python2 llcd.py
> [*] Obtained new session: *****
> 
> [*] Parsing "Illustrator for Fashion Design Drawing Flats" course's chapters
> [*] [12 chapters found]
> [*] --- Parsing "Introduction" chapters's videos
> [*] --- [3 videos found]
> [*] ------ Downloading video "Welcome"
> [*] ------ Downloading video "What is a CAD flat"
> [*] ------ Downloading video "Using the exercise files"
> [*] --- Parsing "1. Getting Started The Basics" chapters's videos
> [*] --- [9 videos found]
> [*] ------ Downloading video "Exploring the workspace"
> [*] ------ Downloading video "Using selection tools"
> [*] ------ Downloading video "Drawing shapes"
> [*] ------ Downloading video "Using color"
> [*] ------ Downloading video "Using the Layers panel"
> [*] ------ Downloading video "Using the Rotate tool"
> [*] ------ Downloading video "Using the Pen tool"
> [*] ------ Downloading video "Using the Reflect and Join commands"
> [*] ------ Downloading video "Using Pathfinder and Shape Builder"
> [*] --- Parsing "2. Creating a Start File" chapters's videos
> [*] --- [3 videos found]
> ```

I have also tried this version and the system is telling me

=============
[Fatal] Your IP may have been temporarily blocked
[Notice] Exception hit
=============

Once again, any idea?

Thank you
Nathan

**Comment by armandhammer** [comment]
Can you still access the videos via the LinkedIn Learning website?
(from the same computer and LinkedIn account)

**Comment by nathan-never** [comment]
Yes, I can access the videos via the Linkedin Learning website from the same computer and the same Linkedin account.
Thank you.
Nathan

**Comment by armandhammer** [comment]
Hmmmm, I don't have any other ideas. I can tell you that it's working for me. I'm running Mac OS 10.14.2 and Python 3.7 (installed via Homebrew). The only modification that I made to the script was to comment out the part where it checks to see if the login was DENIED (this is line 115-117 where it says `if not course.unlocked` and `return`).

I've also had some other issues, where courses with lots of videos like "Audio Recording Techniques" seem to time out or open too many files (I'm not sure) and basically give up before all of the videos are downloaded. I get maybe 80% of the videos. The rest I download manually via Firefox which is quite a pain.

The second issue I've run into is that some courses (like the "Singing Lessons" series) don't have Subtitle files and the script expects every video to have them and gives an error when they don't. I haven't figured out how to get around this. I tried commenting out the code that seems to deal with subtitle files, but it still doesn't work. Fortunately, it seems like less than 10% of courses aren't subtitled.

**Comment by armandhammer** [comment]
Are you only trying to download one course at a time? I also found that trying to put more than one course into config.py did not work. It generates too many open requests/files. If you're only trying one course, how many videos does the course have in total? I found that courses with more than ~50 videos seem more likely to give errors.

**Comment by nathan-never** [comment]
bengarland, thank you again for your prompt reply.

Please give me a title of a course that you can download without any challenges so to use as a "baseline".
All the courses I have tried to download failed.

Nathan

**Comment by armandhammer** [comment]
Try this one, it's really short:

[The Creative Spark Larry Crane Recording Engineer and Music Producer](https://www.linkedin.com/learning/the-creative-spark-larry-crane-recording-engineer-and-music-producer)

**Comment by nathan-never** [comment]
Thank you - 
Nathan

P.S. - you should change your name in "faster-than-light"!

**Comment by nathan-never** [comment]
Same result - I am going to try from another computer.
Best
Nathan

**Comment by nathan-never** [comment]
bengarland - it is working properly from another mac!
Thank you again
Nathan

**Comment by armandhammer** [comment]
I'm not sure if this will help, but I just modified the script so that it doesn't generate subtitle files because I was getting a 'transcript' error for a particular course. As far as I can tell, the video files still download just fine -- there's just no companion .srt file. So try this if you don't care about subtitles. Comment out lines 166, 172, and 177-188:

`#        subtitles = data['elements'][0]['selectedVideo']['transcript']['lines']`
`        duration_in_ms = int(data['elements'][0]['selectedVideo']['durationInSeconds']) * 1000`

`       if not video_exists:`
`           await download_file(video_url, video_file_path)`

`#        await write_subtitles(subtitles, subtitle_file_path, duration_in_ms)`

`    logging.info(f"[~] Done fetching course '{course.name}' Chapter no. {chapter.index} Video no. {video.index}")`


`#async def write_subtitles(subs, output_path, video_duration):`
`#    def subs_to_lines(idx, sub):`
`#        starts_at = sub['transcriptStartAt']`
`#        ends_at = subs[idx]['transcriptStartAt'] if idx < len(subs) else video_duration`
`#        caption = sub['caption']`
`#        return f"{idx}\n" \`
`#               f"{sub_format_time(starts_at)} --> {sub_format_time(ends_at)}\n" \`
`#               f"{caption}\n\n"`

`#    with open(output_path, 'wb') as f:`
`#        for line in starmap(subs_to_lines, enumerate(subs, start=1)):`
`#            f.write(line.encode('utf8'))`

**Comment by nathan-never** [comment]
thank you bengarland - there is/was something strange on my computer as the original script (and various changes) works perfectly on other computers in the same network. 
Best
Nathan

**Comment by SteelBlueVision** [comment]
If you are getting the dreaded 'elements' error, you most likely misspelled the name of the course, or left out a comma in between multiple course names (or included a space in the name or some other spelling error). 99% of the time, this is the culprit, it is just 404'ing trying to access its url.

**Comment by liranbg** [comment]
fixed on #21 && #22

**Comment by hayder1992** [comment]
hey guys i get this error,

Traceback (most recent call last):
  File "C:/Users/sj/Downloads/linkedin-learning-downloader-master/linkedin_learning.py", line 234, in <module>
    loop.run_until_complete(process())
  File "C:\Users\sj\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:/Users/sj/Downloads/linkedin-learning-downloader-master/linkedin_learning.py", line 222, in process
    await fetch_courses()
  File "C:/Users/sj/Downloads/linkedin-learning-downloader-master/linkedin_learning.py", line 102, in fetch_courses
    return await asyncio.gather(*map(fetch_course, COURSES))
  File "C:/Users/sj/Downloads/linkedin-learning-downloader-master/linkedin_learning.py", line 116, in fetch_course
    await fetch_chapters(course)
  File "C:/Users/sj/Downloads/linkedin-learning-downloader-master/linkedin_learning.py", line 128, in fetch_chapters
    await asyncio.gather(*chain.from_iterable(fetch_chapter(course, chapter) for chapter in course.chapters))
  File "C:/Users/sj/Downloads/linkedin-learning-downloader-master/linkedin_learning.py", line 139, in fetch_video_or_wait
    await fetch_video(course, chapter, video)
  File "C:/Users/sj/Downloads/linkedin-learning-downloader-master/linkedin_learning.py", line 165, in fetch_video
    video_url = data['elements'][0]['selectedVideo']['url']['progressiveUrl']
KeyError: 'url'

**Comment by thachnv92** [comment]
@hayder1992 I same you @@
